### ISSUE TITLE
IPC (DelvUI support)

### ISSUE THREAD

**Issue by keysmashes** [sersorrel/WhosTalking#3]
WT should emit an IPC message whenever someone starts/stops talking (or mutes/unmutes, deafens/undeafens, ...). Then DelvUI can track those messages and draw its own voice activity indicators on the party list.

- the IPC interface should refer exclusively to XIV characters, info about Discord users should not be exposed
  - (or, rather: it's not necessarily bad to expose information about Discord users, displaying a Discord username in the party list would be quite neat potentially, but other plugins should absolutely not be required to work out their own ways of mapping Discord users to XIV characters)
  - referring to characters by ContentID is the least fragile way of doing things, but also makes life harder for other plugins; emitting an index into the party list (as displayed in the PartyList addon) is more compatible
- doing IPC means that other plugins will be maintaining their own copies of state, so we cannot rely any more on just redrawing every frame and getting things right that way
  - probably this means we need an extra bonus abstraction layer that handles the translation of "these Discord users are talking" into "these XIV characters are talking" so that that's kept in one place and done once
  - this will probably need to handle things like "a Discord user left while talking" and "a Discord user changed their username while talking" to avoid stuck voice statuses

**Comment by Tischel** [comment]
Went ahead and did this here: https://github.com/sersorrel/WhosTalking/pull/7

Also have the DelvUI side ready: https://github.com/DelvUI/DelvUI/pull/1154
