### ISSUE TITLE
[Bug Report] Having a chocobo out while in a party and in a voice chat with more than 8 people errors.

### ISSUE THREAD

**Issue by thakyZ** [sersorrel/WhosTalking#5]
I recently reported a feedback under the same username as on GitHub, and I didn't include the correct stack trace as another plugin had errored before I could submit the feedback. However, I took the liberty to figure out what caused the error log to be spammed. And the issue is the title. It would appear that when the PartySize object doesn't have a length of 0 and the chocobo is out it counts as a party member, which I would assume is not intended. I have made a fix and will make a pull request.
Here is the correct stack trace:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WhosTalking.Plugin.XivToDiscord(String name, String world) in /work/repo/WhosTalking/Plugin.cs:line 206
   at WhosTalking.Plugin.DrawOverlay() in /work/repo/WhosTalking/Plugin.cs:line 194
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 96
19:43:26.059 | ERR Exception during raise of "Void Draw()"
```

**Comment by keysmashes** [comment]
This should be fixed in 0.2.1.0, which will be available once https://github.com/goatcorp/DalamudPluginsD17/pull/2117 is merged. Thanks again for reporting it!
